services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_new
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      timeout: 5s
      retries: 10

  api:
    build:
      context: backend/
      dockerfile: Dockerfile
    container_name: my_api_new
    environment:
      - PORT=${PORT}
    ports:
      - '5000:5000'
    depends_on:
      - postgres
    env_file:
      - .env

  fe:
    build:
      context: frontend/
      dockerfile: Dockerfile
    container_name: CLIENT_NEW
    environment:
      - PORT=${PORT}
    ports:
      - 5173:5173

  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   container_name: pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=pgadmin4
  #   ports:
  #     - '5050:80'
  #   depends_on:
  #     - postgres
